name: 'Deploy static_content to S3'
on:
  push:
    branches:
      - master
    paths:
      - 'static_content/**'
env:
  bucketName: ${{ secrets.AWS_STATIC_CONTENT_BUCKET_NAME }}
  cloudFrontDeploymentId: ${{ secrets.AWS_CLOUDFRONT_DEPLOYMENT_ID }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Deploy to AWS'
        run: |
          aws s3 sync --sse --delete . s3://${{ env.bucketName }}
          aws cloudfront create-invalidation --distribution-id ${{ env.cloudFrontDeploymentId }} --paths "/*"
        working-directory: 'static_content'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
